targets:
  $default:
    builders:
      build_web_compilers:entrypoint:
        generate_for:
          - lib/build.js.dart
        options:
          compiler: dart2js
          dart2js_args:
            - -O2