name: saslprep
authors:
  - Richard Burkhardt <my.richidd@gmail.com>
homepage: https://github.com/konsultaner/saslprep-dart
version: 1.0.0-dev.1
description: >-
  This package provides the Stringprep (rfc4013) Profile for User Names and Passwords for dart. A port of https://github.com/reklatsmasters/saslprep to the dart lang
dependencies:
  unorm_dart: 0.1.2
dev_dependencies:
  test: ^1.12.0
environment:
  sdk: ">=2.3.0 <3.0.0"
